name: blah blah blah
on: [push]
jobs:
  go:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cole-miller/jepsen-dqlite-docker:0.4.0
      options: --privileged
    steps:
      - name: jepsen
        uses: ./.github/workflows/test-build-run.yml
        with:
          workloads: "['append']"
          nemeses: "['none']"
          disk: "['0']"
