name: blah blah blah
on: [push]
jobs:
  go:
    runs-on: ubuntu-22.04
    steps:
      - name: sysctl
        run: |
          sudo sysctl -w kernel.core_pattern=core
      - name: container
        uses: cole-miller/jepsen-dqlite-docker/.github/workflows/test-build-run.yml@master
        with:
          workloads: "['append']"
          nemeses: "['none']"
          disk: "['0']"

