name: blah blah blah
on: [push]
jobs:
  go:
    uses: ./.github/workflows/test-build-run.yml
    with:
      workloads: "['append']"
      nemeses: "['none']"
      disk: "['0']"
      jepsen-repo: "https://github.com/cole-miller/jepsen"
      jepsen-branch: "sed"
